import * as fs from "fs";
import * as path from "path";
import { FortranDependency, DEP_FILE_NAME, DependencyFile } from "./dependencyModel";

export function readDependencies(workspaceFolder: string): DependencyFile {
  const depPath = path.join(workspaceFolder, DEP_FILE_NAME);
  if (!fs.existsSync(depPath)) {
    return { dependencies: [] };
  }
  const raw = fs.readFileSync(depPath, "utf8");
  return JSON.parse(raw) as DependencyFile;
}

export function writeDependencies(workspaceFolder: string, deps: DependencyFile) {
  const depPath = path.join(workspaceFolder, DEP_FILE_NAME);
  fs.mkdirSync(path.dirname(depPath), { recursive: true });
  fs.writeFileSync(depPath, JSON.stringify(deps, null, 2), "utf8");
}

export function generateDependenciesCMake(workspaceFolder: string, deps: DependencyFile) {
  const cmakeDir = path.join(workspaceFolder, "cmake");
  fs.mkdirSync(cmakeDir, { recursive: true });
  const filePath = path.join(cmakeDir, "dependencies.cmake");

  const lines: string[] = [];
  lines.push("# Auto-generated by Fortran CMake Dependency Helper");
  lines.push("# Do not edit manually; use the VSCode extension instead.");
  lines.push("");

  for (const dep of deps.dependencies) {
    const libName = dep.name;
    const cmakePackageName = dep.cmakePackage || dep.name;
    const tag = dep.tag || "main";

    lines.push(`# Dependency: ${dep.name}`);
    if (dep.version) {
      lines.push(`find_package(${libName} ${dep.version} QUIET)`);
    } else {
      lines.push(`find_package(${libName} QUIET)`);
    }
    lines.push(``);
    lines.push(`if(NOT ${libName}_FOUND)`);
    lines.push(`  message(STATUS "${libName} not found; using FetchContent fallback")`);
    lines.push(`  include(FetchContent)`);
    lines.push(`  FetchContent_Declare(`);
    lines.push(`    ${dep.name}`);
    lines.push(`    GIT_REPOSITORY ${dep.repo}`);
    lines.push(`    GIT_TAG ${tag}`);
    lines.push(`  )`);
    lines.push(`  FetchContent_MakeAvailable(${dep.name})`);
    if (cmakePackageName !== libName) {
      lines.push(`  if(NOT TARGET ${cmakePackageName})`);
      lines.push(`    add_library(${cmakePackageName} INTERFACE IMPORTED GLOBAL)`);
      lines.push(`  endif()`);
      lines.push(`  target_link_libraries(${cmakePackageName} INTERFACE ${libName})`);
    }
    lines.push(`endif()`);
    lines.push(``);
  }

  fs.writeFileSync(filePath, lines.join("\n"), "utf8");
}

export function generateProjectLinkCMake(workspaceFolder: string, deps: DependencyFile) {
  const cmakeListsPath = path.join(workspaceFolder, "CMakeLists.txt");
  if (!fs.existsSync(cmakeListsPath)) {
    return;
  }

  let content = fs.readFileSync(cmakeListsPath, "utf8");
  content = content.replace(/\n*target_link_libraries\(\$\{PROJECT_NAME\}\s+PRIVATE\s+.*\)\s*\n?/g, "\n");

  const depsList = deps.dependencies
    .map(dep => dep.cmakePackage || dep.name)
    .join(" ");

  if (depsList.length === 0) {
    fs.writeFileSync(cmakeListsPath, content, "utf8");
    return;
  }

  const linkLine = `target_link_libraries(${"${PROJECT_NAME}"} PRIVATE ${depsList})`;

  if (content.includes("add_executable(")) {
    content = content.replace(
      /add_executable\([^\n]+\n?/,
      match => `${match.trimEnd()}\n${linkLine}\n`
    );
  } else {
    content += `\n${linkLine}\n`;
  }

  fs.writeFileSync(cmakeListsPath, content, "utf8");
}

export function ensureBaseCMakeFiles(workspaceFolder: string, projectName: string) {
  const cmakeListsPath = path.join(workspaceFolder, "CMakeLists.txt");
  const srcDir = path.join(workspaceFolder, "src");
  const mainPath = path.join(srcDir, "main.f90");

  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
  }

  if (!fs.existsSync(mainPath)) {
    const mainContent = `program ${sanitizeProgramName(projectName)}
  implicit none

  print *, "Hello from ${projectName}!"

end program ${sanitizeProgramName(projectName)}
`;
    fs.writeFileSync(mainPath, mainContent, "utf8");
  }

  if (!fs.existsSync(cmakeListsPath)) {
    const cmakeContent = `cmake_minimum_required(VERSION 3.20)
project(${projectName} LANGUAGES Fortran)

include(cmake/dependencies.cmake)

enable_language(Fortran)

add_executable(${projectName} src/main.f90)
`;
    const cmakeDir = path.join(workspaceFolder, "cmake");
    fs.mkdirSync(cmakeDir, { recursive: true });
    fs.writeFileSync(cmakeListsPath, cmakeContent, "utf8");

    const depsPath = path.join(cmakeDir, "dependencies.cmake");
    if (!fs.existsSync(depsPath)) {
      fs.writeFileSync(
        depsPath,
        "# Auto-generated by Fortran CMake Dependency Helper\n\n",
        "utf8"
      );
    }
  }
}

function sanitizeProgramName(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}
