import * as fs from "fs";
import * as path from "path";
import { FortranDependency, DEP_FILE_NAME, DependencyFile, FEATURES_TARGET } from "./dependencyModel";

export function readDependencies(workspaceFolder: string): DependencyFile {
  const depPath = path.join(workspaceFolder, DEP_FILE_NAME);
  if (!fs.existsSync(depPath)) {
    return { dependencies: [] };
  }
  const raw = fs.readFileSync(depPath, "utf8");
  return JSON.parse(raw) as DependencyFile;
}

export function writeDependencies(workspaceFolder: string, deps: DependencyFile) {
  const depPath = path.join(workspaceFolder, DEP_FILE_NAME);
  fs.mkdirSync(path.dirname(depPath), { recursive: true });
  fs.writeFileSync(depPath, JSON.stringify(deps, null, 2), "utf8");
}

export function generateDependenciesCMake(workspaceFolder: string, deps: DependencyFile) {
  const cmakeDir = path.join(workspaceFolder, "cmake");
  fs.mkdirSync(cmakeDir, { recursive: true });
  const filePath = path.join(cmakeDir, "dependencies.cmake");

  const lines: string[] = [];
  lines.push("# Auto-generated by Fortran CMake Dependency Helper");
  lines.push("# Do not edit manually; use the VSCode extension instead.");
  lines.push("");

  for (const dep of deps.dependencies) {
    const libName = dep.name;
    const cmakePackageName = dep.cmakePackage || dep.name;
    const tag = dep.tag || "main";

    lines.push(`# Dependency: ${dep.name}`);
    if (dep.version) {
      lines.push(`find_package(${libName} ${dep.version} QUIET)`);
    } else {
      lines.push(`find_package(${libName} QUIET)`);
    }
    lines.push(``);
    lines.push(`if(NOT ${libName}_FOUND)`);
    lines.push(`  message(STATUS "${libName} not found; using FetchContent fallback")`);
    lines.push(`  include(FetchContent)`);
    lines.push(`  FetchContent_Declare(`);
    lines.push(`    ${dep.name}`);
    lines.push(`    GIT_REPOSITORY ${dep.repo}`);
    lines.push(`    GIT_TAG ${tag}`);
    lines.push(`  )`);
    lines.push(`  FetchContent_MakeAvailable(${dep.name})`);
    if (cmakePackageName !== libName) {
      lines.push(`  if(NOT TARGET ${cmakePackageName})`);
      lines.push(`    add_library(${cmakePackageName} INTERFACE IMPORTED GLOBAL)`);
      lines.push(`  endif()`);
      lines.push(`  target_link_libraries(${cmakePackageName} INTERFACE ${libName})`);
    }
    lines.push(`endif()`);
    lines.push(``);
  }

  fs.writeFileSync(filePath, lines.join("\n"), "utf8");
}

export function generateFeaturesCMake(workspaceFolder: string, deps: DependencyFile) {
  const cmakeDir = path.join(workspaceFolder, "cmake");
  fs.mkdirSync(cmakeDir, { recursive: true });
  const filePath = path.join(cmakeDir, "features.cmake");

  const openmp = deps.features?.openmp === true;
  const coarrays = deps.features?.coarrays === true;
  const parallelDoConcurrent = deps.features?.parallelDoConcurrent === true;

  const lines: string[] = [];
  lines.push("# Auto-generated by Fortran CMake Dependency Helper");
  lines.push("# Do not edit manually; use the VSCode extension instead.");
  lines.push("");
  lines.push(`if(NOT TARGET ${FEATURES_TARGET})`);
  lines.push(`  add_library(${FEATURES_TARGET} INTERFACE)`);
  lines.push("endif()");
  lines.push("");

  if (openmp) {
    lines.push("# OpenMP");
    lines.push("find_package(OpenMP REQUIRED COMPONENTS Fortran)");
    lines.push(`target_link_libraries(${FEATURES_TARGET} INTERFACE OpenMP::OpenMP_Fortran)`);
    lines.push("");
  }

  if (coarrays) {
    const fallback = deps.features?.coarrayFallback ?? "single";
    lines.push("# Coarrays: pick the flags matching the active Fortran compiler");
    lines.push(
      `set(FCDH_COARRAY_FALLBACK "${fallback}" CACHE STRING "What to do when OpenCoarrays is missing: single, fetch, or error")`
    );
    lines.push(
      'set_property(CACHE FCDH_COARRAY_FALLBACK PROPERTY STRINGS single fetch error)'
    );
    lines.push(
      `set(FCDH_OPENCOARRAYS_GIT_TAG "2.10.2" CACHE STRING "OpenCoarrays tag used by the fetch fallback")`
    );
    lines.push('set(_fcdh_coarray_compile_flags "")');
    lines.push('set(_fcdh_coarray_link_flags "")');
    lines.push('if(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")');
    lines.push("  find_package(OpenCoarrays QUIET)");
    lines.push("  if(OpenCoarrays_FOUND)");
    lines.push("    set(_fcdh_coarray_compile_flags -fcoarray=lib)");
    lines.push(`    target_link_libraries(${FEATURES_TARGET} INTERFACE OpenCoarrays::caf_mpi)`);
    lines.push('  elseif(FCDH_COARRAY_FALLBACK STREQUAL "fetch")');
    lines.push("    find_package(MPI QUIET COMPONENTS Fortran)");
    lines.push("    if(NOT MPI_Fortran_FOUND)");
    lines.push(
      '      message(FATAL_ERROR "OpenCoarrays fallback is set to \'fetch\' but no Fortran MPI installation was found. Install MPI, install OpenCoarrays, or set FCDH_COARRAY_FALLBACK=single.")'
    );
    lines.push("    endif()");
    lines.push('    message(STATUS "OpenCoarrays not found; building it via FetchContent")');
    lines.push("    include(FetchContent)");
    lines.push("    FetchContent_Declare(");
    lines.push("      OpenCoarrays");
    lines.push("      GIT_REPOSITORY https://github.com/sourceryinstitute/OpenCoarrays.git");
    lines.push("      GIT_TAG ${FCDH_OPENCOARRAYS_GIT_TAG}");
    lines.push("    )");
    lines.push('    set(OpenCoarrays_BUILD_TESTING OFF CACHE BOOL "" FORCE)');
    lines.push('    set(BUILD_TESTING OFF CACHE BOOL "" FORCE)');
    lines.push("    FetchContent_MakeAvailable(OpenCoarrays)");
    lines.push("    if(TARGET OpenCoarrays::caf_mpi)");
    lines.push(`      target_link_libraries(${FEATURES_TARGET} INTERFACE OpenCoarrays::caf_mpi)`);
    lines.push("    elseif(TARGET caf_mpi)");
    lines.push(`      target_link_libraries(${FEATURES_TARGET} INTERFACE caf_mpi)`);
    lines.push("    else()");
    lines.push(
      '      message(FATAL_ERROR "OpenCoarrays was fetched but no caf_mpi target was produced.")'
    );
    lines.push("    endif()");
    lines.push("    set(_fcdh_coarray_compile_flags -fcoarray=lib)");
    lines.push('  elseif(FCDH_COARRAY_FALLBACK STREQUAL "error")');
    lines.push(
      '    message(FATAL_ERROR "OpenCoarrays not found. Install it (e.g. apt install libcaf-openmpi-dev, brew install opencoarrays, spack install opencoarrays), point CMAKE_PREFIX_PATH at it, or set FCDH_COARRAY_FALLBACK to single or fetch.")'
    );
    lines.push("  else()");
    lines.push(
      '    message(WARNING "OpenCoarrays not found; building coarrays in single-image mode. Multi-image runs will not work. Set FCDH_COARRAY_FALLBACK to fetch or error to change this.")'
    );
    lines.push("    set(_fcdh_coarray_compile_flags -fcoarray=single)");
    lines.push("  endif()");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID MATCHES "^Intel")');
    lines.push("  if(WIN32)");
    lines.push("    set(_fcdh_coarray_compile_flags /Qcoarray:shared)");
    lines.push("    set(_fcdh_coarray_link_flags /Qcoarray:shared)");
    lines.push("  else()");
    lines.push("    set(_fcdh_coarray_compile_flags -coarray=shared)");
    lines.push("    set(_fcdh_coarray_link_flags -coarray=shared)");
    lines.push("  endif()");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "NAG")');
    lines.push("  set(_fcdh_coarray_compile_flags -coarray=cosmp)");
    lines.push("  set(_fcdh_coarray_link_flags -coarray=cosmp)");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Cray")');
    lines.push('  message(STATUS "Cray Fortran enables coarrays by default; no extra flags added")');
    lines.push("else()");
    lines.push(
      '  message(WARNING "Coarray flags are unknown for Fortran compiler ${CMAKE_Fortran_COMPILER_ID}")'
    );
    lines.push("endif()");
    lines.push("");
    lines.push("if(_fcdh_coarray_compile_flags)");
    lines.push(
      `  target_compile_options(${FEATURES_TARGET} INTERFACE $<$<COMPILE_LANGUAGE:Fortran>:\${_fcdh_coarray_compile_flags}>)`
    );
    lines.push("endif()");
    lines.push("if(_fcdh_coarray_link_flags)");
    lines.push(`  target_link_options(${FEATURES_TARGET} INTERFACE \${_fcdh_coarray_link_flags})`);
    lines.push("endif()");
    lines.push("");
  }

  if (parallelDoConcurrent) {
    lines.push("# Parallel DO CONCURRENT: pick the flags matching the active Fortran compiler");
    lines.push("# Some compilers implement it on top of OpenMP, so OpenMP is pulled in when needed.");
    lines.push('set(_fcdh_doconcurrent_compile_flags "")');
    lines.push('set(_fcdh_doconcurrent_link_flags "")');
    lines.push("set(_fcdh_doconcurrent_needs_openmp FALSE)");
    lines.push('if(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")');
    lines.push("  # gfortran relies on the auto-parallelizer (needs -O2 or higher) backed by libgomp");
    lines.push("  set(_fcdh_doconcurrent_compile_flags -ftree-parallelize-loops=4)");
    lines.push("  set(_fcdh_doconcurrent_needs_openmp TRUE)");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "IntelLLVM")');
    lines.push("  set(_fcdh_doconcurrent_needs_openmp TRUE)");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")');
    lines.push("  if(WIN32)");
    lines.push("    set(_fcdh_doconcurrent_compile_flags /Qparallel)");
    lines.push("    set(_fcdh_doconcurrent_link_flags /Qparallel)");
    lines.push("  else()");
    lines.push("    set(_fcdh_doconcurrent_compile_flags -parallel)");
    lines.push("    set(_fcdh_doconcurrent_link_flags -parallel)");
    lines.push("  endif()");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID MATCHES "NVHPC|PGI")');
    lines.push("  set(_fcdh_doconcurrent_compile_flags -stdpar=multicore)");
    lines.push("  set(_fcdh_doconcurrent_link_flags -stdpar=multicore)");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID MATCHES "Flang")');
    lines.push("  set(_fcdh_doconcurrent_compile_flags -fdo-concurrent-to-openmp=host)");
    lines.push("  set(_fcdh_doconcurrent_needs_openmp TRUE)");
    lines.push('elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Cray")');
    lines.push("  set(_fcdh_doconcurrent_compile_flags -h thread_do_concurrent)");
    lines.push("else()");
    lines.push(
      '  message(WARNING "Parallel DO CONCURRENT flags are unknown for Fortran compiler ${CMAKE_Fortran_COMPILER_ID}")'
    );
    lines.push("endif()");
    lines.push("");
    lines.push("if(_fcdh_doconcurrent_needs_openmp)");
    lines.push("  find_package(OpenMP REQUIRED COMPONENTS Fortran)");
    if (openmp) {
      lines.push("  # OpenMP was already linked above for the explicit OpenMP feature");
    } else {
      lines.push(`  target_link_libraries(${FEATURES_TARGET} INTERFACE OpenMP::OpenMP_Fortran)`);
    }
    lines.push("endif()");
    lines.push("");
    lines.push("if(_fcdh_doconcurrent_compile_flags)");
    lines.push(
      `  target_compile_options(${FEATURES_TARGET} INTERFACE $<$<COMPILE_LANGUAGE:Fortran>:\${_fcdh_doconcurrent_compile_flags}>)`
    );
    lines.push("endif()");
    lines.push("if(_fcdh_doconcurrent_link_flags)");
    lines.push(`  target_link_options(${FEATURES_TARGET} INTERFACE \${_fcdh_doconcurrent_link_flags})`);
    lines.push("endif()");
    lines.push("");
  }

  fs.writeFileSync(filePath, lines.join("\n"), "utf8");
}

export function generateProjectLinkCMake(workspaceFolder: string, deps: DependencyFile) {
  const cmakeListsPath = path.join(workspaceFolder, "CMakeLists.txt");
  if (!fs.existsSync(cmakeListsPath)) {
    return;
  }

  let content = fs.readFileSync(cmakeListsPath, "utf8");
  content = content.replace(/\n*target_link_libraries\(\$\{PROJECT_NAME\}\s+PRIVATE\s+.*\)\s*\n?/g, "\n");
  content = ensureFeaturesInclude(content);

  const linkTargets = deps.dependencies.map(dep => dep.cmakePackage || dep.name);
  if (deps.features?.openmp || deps.features?.coarrays || deps.features?.parallelDoConcurrent) {
    linkTargets.push(FEATURES_TARGET);
  }
  const depsList = linkTargets.join(" ");

  if (depsList.length === 0) {
    fs.writeFileSync(cmakeListsPath, content, "utf8");
    return;
  }

  const linkLine = `target_link_libraries(${"${PROJECT_NAME}"} PRIVATE ${depsList})`;

  if (content.includes("add_executable(")) {
    content = content.replace(
      /add_executable\([^\n]+\n?/,
      match => `${match.trimEnd()}\n${linkLine}\n`
    );
  } else {
    content += `\n${linkLine}\n`;
  }

  fs.writeFileSync(cmakeListsPath, content, "utf8");
}

export function ensureBaseCMakeFiles(workspaceFolder: string, projectName: string) {
  const cmakeListsPath = path.join(workspaceFolder, "CMakeLists.txt");
  const srcDir = path.join(workspaceFolder, "src");
  const mainPath = path.join(srcDir, "main.f90");

  if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
  }

  if (!fs.existsSync(mainPath)) {
    const mainContent = `program ${sanitizeProgramName(projectName)}
  implicit none

  print *, "Hello from ${projectName}!"

end program ${sanitizeProgramName(projectName)}
`;
    fs.writeFileSync(mainPath, mainContent, "utf8");
  }

  if (!fs.existsSync(cmakeListsPath)) {
    const cmakeContent = `cmake_minimum_required(VERSION 3.20)
project(${projectName} LANGUAGES Fortran)

include(cmake/dependencies.cmake)
include(cmake/features.cmake)

enable_language(Fortran)

add_executable(${projectName} src/main.f90)
`;
    const cmakeDir = path.join(workspaceFolder, "cmake");
    fs.mkdirSync(cmakeDir, { recursive: true });
    fs.writeFileSync(cmakeListsPath, cmakeContent, "utf8");

    const depsPath = path.join(cmakeDir, "dependencies.cmake");
    if (!fs.existsSync(depsPath)) {
      fs.writeFileSync(
        depsPath,
        "# Auto-generated by Fortran CMake Dependency Helper\n\n",
        "utf8"
      );
    }
  }

  const featuresPath = path.join(workspaceFolder, "cmake", "features.cmake");
  if (!fs.existsSync(featuresPath)) {
    generateFeaturesCMake(workspaceFolder, { dependencies: [] });
  }
}

function ensureFeaturesInclude(content: string): string {
  if (/include\(\s*cmake\/features\.cmake\s*\)/.test(content)) {
    return content;
  }

  const depsInclude = /include\(\s*cmake\/dependencies\.cmake\s*\)[^\n]*\n?/;
  if (depsInclude.test(content)) {
    return content.replace(depsInclude, match => `${match.trimEnd()}\ninclude(cmake/features.cmake)\n`);
  }

  const projectCall = /project\([^\n]*\)[^\n]*\n?/;
  if (projectCall.test(content)) {
    return content.replace(projectCall, match => `${match.trimEnd()}\n\ninclude(cmake/features.cmake)\n`);
  }

  return `include(cmake/features.cmake)\n${content}`;
}

function sanitizeProgramName(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_");
}
